### ISSUE TITLE
Vylepšit chování při kolizi tanku se stěnou.

### ISSUE THREAD

**Issue by marvertin** [RademCZ/tankhunt#2]
Při najetí tanku do stěny tank vykonává posuvný pohyb podle stěny, což je nepřirozené.

Lepší by bylo uvažovat sílu působící na rohu tanku kolmo od stěny, tuto sílu rozložit na moment a sílu působící v těžišti, tak by se díky působícímu momentu začal otáčet a při zohlednění setrvačnosti by také odskočil. Přitom je potřeba vhodně zvolit pružnost nárazu.

**Comment by radverg** [comment]
Nemám zatím v plánu měnit chování po kolizi se stěnami, pouze opravit záseky. Nejen že je to zbytečně složité, ale navíc by to zhoršilo ovládání a vzhledem k tomu, že to není simulátor, tak to není ani nutné. Pokud bych přece jen chtěl kolize vylepšit, budu to dělat jako poslední věc, protože zrovna toto stojí nejvíc času a úsilí.
