### ISSUE TITLE
Vytvořit sestavovací skript a vyhodit z gitu, co tam nepatří.

### ISSUE THREAD

**Issue by marvertin** [RademCZ/tankhunt#3]
Do verzovacího systému se dávají jen primární soubory, ne soubory odvozené.

Vyhoď proto` *.js` a `node_modules` a místo toho stvoř skript, který vše vyrobí. Nejlépe pomocí `npm`.

**Comment by radverg** [comment]
Hotovo, zbývá dodělat sestavovací skript.
